rename : "jenkins ci/cd 테스트"

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -1,145 +1,145 @@
-name: Java CD with Maven
-
-on:
-  push:
-    branches: [ "develop", "main" ]
-
-permissions: write-all
-
-jobs:
-  deploy:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout Repository
-        uses: actions/checkout@v3
-
-      - name: Set up SSH
-        env:
-          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-        run: |
-          mkdir -p ~/.ssh
-          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/github_rsa
-          chmod 400 ~/.ssh/github_rsa
-          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
-
-      - name: Copy project files to Remote Server
-        env:
-          REMOTE_USER: ${{ secrets.SSH_USER }}
-          REMOTE_HOST: ${{ secrets.SSH_HOST }}
-          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
-        run: |
-          scp -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no Dockerfile ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/Dockerfile
-          scp -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no pom.xml ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/pom.xml
-          scp -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no -r src ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/src
-          scp -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no src/main/resources/application-prod.yml ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/src/main/resources/application-prod.yml
-
-      - name: Check Dockerfile on Remote Server
-        env:
-          REMOTE_USER: ${{ secrets.SSH_USER }}
-          REMOTE_HOST: ${{ secrets.SSH_HOST }}
-          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
-        run: |
-          ssh -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} "ls -la ${REMOTE_DIR}/Dockerfile"
-          ssh -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} "ls -la ${REMOTE_DIR}/pom.xml"
-          ssh -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} "ls -la ${REMOTE_DIR}/src"
-          ssh -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} "ls -la ${REMOTE_DIR}/src/main/resources/application-prod.yml"
-
-      - name: Deploy JAR on Remote Server
-        env:
-          REMOTE_USER: ${{ secrets.SSH_USER }}
-          REMOTE_HOST: ${{ secrets.SSH_HOST }}
-          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
-          YES25_5_MYSQL_PASSWORD: ${{ secrets.YES25_5_MYSQL_PASSWORD }}
-          EUREKA_SERVER_HOSTNAME: ${{ secrets.EUREKA_SERVER_HOSTNAME }}
-          EUREKA_SERVER_PORT: ${{ secrets.EUREKA_SERVER_PORT }}
-        run: |
-          ssh -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} << EOF
-            cd ${REMOTE_DIR}
-            if [ ! -f Dockerfile ]; then
-              echo "Dockerfile not found!"
-              exit 1
-            fi
-            docker build -t books-users-app .
-            docker stop books-users-app || true
-            docker rm books-users-app || true
-            docker run -d -p 8060:8060 --name books-users-app \
-              -e YES25_5_MYSQL_PASSWORD=${YES25_5_MYSQL_PASSWORD} \
-              -e EUREKA_SERVER_HOSTNAME=${EUREKA_SERVER_HOSTNAME} \
-              -e EUREKA_SERVER_PORT=${EUREKA_SERVER_PORT} \
-              books-users-app
-          EOF
-
-      - name: Send Deployment Status to Dooray
-        if: success()
-        uses: actions/github-script@v6
-        env:
-          PR_URL: ${{ github.event.pull_request.html_url }}
-          PR_ACTOR: ${{ github.actor }}
-          PR_TITLE: ${{ github.event.pull_request.title }}
-          DOORAY_WEBHOOK_URL: ${{ secrets.DOORAY_WEBHOOK_URL }}
-        with:
-          script: |
-            const webhookUrl = process.env.DOORAY_WEBHOOK_URL;
-            const payload = {
-              botName: "도서 회원 서버 Bot",
-              botIconImage: "https://www.tistory.com/favicon.ico",
-              text: "도서 회원 서버의 배포가 성공적으로 완료되었습니다!",
-              attachments: [
-                {
-                  title: "Pull Request URL",
-                  titleLink: process.env.PR_URL,
-                  color: "green",
-                  text: `PR 제목: ${process.env.PR_TITLE}, PR 작성자: ${process.env.PR_ACTOR}`
-                }
-              ]
-            };
-
-            const response = await fetch(webhookUrl, {
-              method: 'POST',
-              headers: {
-                'Content-Type': 'application/json'
-              },
-              body: JSON.stringify(payload)
-            });
-
-            if (!response.ok) {
-              throw new Error(`Failed to send webhook: ${response.statusText}`);
-            }
-
-      - name: Send Deployment Failure to Dooray
-        if: failure()
-        uses: actions/github-script@v6
-        env:
-          PR_URL: ${{ github.event.pull_request.html_url }}
-          PR_TITLE: ${{ github.event.pull_request.title }}
-          PR_ACTOR: ${{ github.actor }}
-          DOORAY_WEBHOOK_URL: ${{ secrets.DOORAY_WEBHOOK_URL }}
-        with:
-          script: |
-            const webhookUrl = process.env.DOORAY_WEBHOOK_URL;
-            const payload = {
-              botName: "도서 회원 서버 Bot",
-              botIconImage: "https://www.tistory.com/favicon.ico",
-              text: "도서 회원 서버의 배포가 실패했습니다...",
-              attachments: [
-                {
-                  title: "Pull Request URL",
-                  titleLink: process.env.PR_URL,
-                  color: "red",
-                  text: `PR 제목: ${process.env.PR_TITLE}, PR 작성자: ${process.env.PR_ACTOR}`
-                }
-              ]
-            };
-
-            const response = await fetch(webhookUrl, {
-              method: 'POST',
-              headers: {
-                'Content-Type': 'application/json'
-              },
-              body: JSON.stringify(payload)
-            });
-
-            if (!response.ok) {
-              throw new Error(`Failed to send webhook: ${response.statusText}`);
-            }
+#name: Java CD with Maven
+#
+#on:
+#  push:
+#    branches: [ "develop", "main" ]
+#
+#permissions: write-all
+#
+#jobs:
+#  deploy:
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - name: Checkout Repository
+#        uses: actions/checkout@v3
+#
+#      - name: Set up SSH
+#        env:
+#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+#        run: |
+#          mkdir -p ~/.ssh
+#          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/github_rsa
+#          chmod 400 ~/.ssh/github_rsa
+#          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
+#
+#      - name: Copy project files to Remote Server
+#        env:
+#          REMOTE_USER: ${{ secrets.SSH_USER }}
+#          REMOTE_HOST: ${{ secrets.SSH_HOST }}
+#          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
+#        run: |
+#          scp -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no Dockerfile ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/Dockerfile
+#          scp -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no pom.xml ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/pom.xml
+#          scp -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no -r src ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/src
+#          scp -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no src/main/resources/application-prod.yml ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}/src/main/resources/application-prod.yml
+#
+#      - name: Check Dockerfile on Remote Server
+#        env:
+#          REMOTE_USER: ${{ secrets.SSH_USER }}
+#          REMOTE_HOST: ${{ secrets.SSH_HOST }}
+#          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
+#        run: |
+#          ssh -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} "ls -la ${REMOTE_DIR}/Dockerfile"
+#          ssh -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} "ls -la ${REMOTE_DIR}/pom.xml"
+#          ssh -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} "ls -la ${REMOTE_DIR}/src"
+#          ssh -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} "ls -la ${REMOTE_DIR}/src/main/resources/application-prod.yml"
+#
+#      - name: Deploy JAR on Remote Server
+#        env:
+#          REMOTE_USER: ${{ secrets.SSH_USER }}
+#          REMOTE_HOST: ${{ secrets.SSH_HOST }}
+#          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
+#          YES25_5_MYSQL_PASSWORD: ${{ secrets.YES25_5_MYSQL_PASSWORD }}
+#          EUREKA_SERVER_HOSTNAME: ${{ secrets.EUREKA_SERVER_HOSTNAME }}
+#          EUREKA_SERVER_PORT: ${{ secrets.EUREKA_SERVER_PORT }}
+#        run: |
+#          ssh -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no ${REMOTE_USER}@${REMOTE_HOST} << EOF
+#            cd ${REMOTE_DIR}
+#            if [ ! -f Dockerfile ]; then
+#              echo "Dockerfile not found!"
+#              exit 1
+#            fi
+#            docker build -t books-users-app .
+#            docker stop books-users-app || true
+#            docker rm books-users-app || true
+#            docker run -d -p 8060:8060 --name books-users-app \
+#              -e YES25_5_MYSQL_PASSWORD=${YES25_5_MYSQL_PASSWORD} \
+#              -e EUREKA_SERVER_HOSTNAME=${EUREKA_SERVER_HOSTNAME} \
+#              -e EUREKA_SERVER_PORT=${EUREKA_SERVER_PORT} \
+#              books-users-app
+#          EOF
+#
+#      - name: Send Deployment Status to Dooray
+#        if: success()
+#        uses: actions/github-script@v6
+#        env:
+#          PR_URL: ${{ github.event.pull_request.html_url }}
+#          PR_ACTOR: ${{ github.actor }}
+#          PR_TITLE: ${{ github.event.pull_request.title }}
+#          DOORAY_WEBHOOK_URL: ${{ secrets.DOORAY_WEBHOOK_URL }}
+#        with:
+#          script: |
+#            const webhookUrl = process.env.DOORAY_WEBHOOK_URL;
+#            const payload = {
+#              botName: "도서 회원 서버 Bot",
+#              botIconImage: "https://www.tistory.com/favicon.ico",
+#              text: "도서 회원 서버의 배포가 성공적으로 완료되었습니다!",
+#              attachments: [
+#                {
+#                  title: "Pull Request URL",
+#                  titleLink: process.env.PR_URL,
+#                  color: "green",
+#                  text: `PR 제목: ${process.env.PR_TITLE}, PR 작성자: ${process.env.PR_ACTOR}`
+#                }
+#              ]
+#            };
+#
+#            const response = await fetch(webhookUrl, {
+#              method: 'POST',
+#              headers: {
+#                'Content-Type': 'application/json'
+#              },
+#              body: JSON.stringify(payload)
+#            });
+#
+#            if (!response.ok) {
+#              throw new Error(`Failed to send webhook: ${response.statusText}`);
+#            }
+#
+#      - name: Send Deployment Failure to Dooray
+#        if: failure()
+#        uses: actions/github-script@v6
+#        env:
+#          PR_URL: ${{ github.event.pull_request.html_url }}
+#          PR_TITLE: ${{ github.event.pull_request.title }}
+#          PR_ACTOR: ${{ github.actor }}
+#          DOORAY_WEBHOOK_URL: ${{ secrets.DOORAY_WEBHOOK_URL }}
+#        with:
+#          script: |
+#            const webhookUrl = process.env.DOORAY_WEBHOOK_URL;
+#            const payload = {
+#              botName: "도서 회원 서버 Bot",
+#              botIconImage: "https://www.tistory.com/favicon.ico",
+#              text: "도서 회원 서버의 배포가 실패했습니다...",
+#              attachments: [
+#                {
+#                  title: "Pull Request URL",
+#                  titleLink: process.env.PR_URL,
+#                  color: "red",
+#                  text: `PR 제목: ${process.env.PR_TITLE}, PR 작성자: ${process.env.PR_ACTOR}`
+#                }
+#              ]
+#            };
+#
+#            const response = await fetch(webhookUrl, {
+#              method: 'POST',
+#              headers: {
+#                'Content-Type': 'application/json'
+#              },
+#              body: JSON.stringify(payload)
+#            });
+#
+#            if (!response.ok) {
+#              throw new Error(`Failed to send webhook: ${response.statusText}`);
+#            }
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,141 +1,141 @@
-name: Java CI with Docker
-
-on:
-  pull_request:
-    branches: [ "develop" ]
-
-permissions: write-all
-
-jobs:
-  build:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-
-      - name: Verify Dockerfile exists
-        run: |
-          if [ ! -f Dockerfile ]; then
-            echo "Dockerfile not found!"
-            exit 1
-          fi
-
-      - name: Build Docker image
-        run: |
-          docker build --no-cache -t books-users-app .
-
-      - name: Run Maven tests in Docker
-        run: |
-          docker run --rm books-users-app mvn clean verify sonar:sonar \
-          -Dspring.profile.active=ci \
-          -Dsonar.projectKey=yes-25-5-books-users \
-          -Dsonar.projectName='yes-25-5-books-users' \
-          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
-          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
-
-      - name: Build Maven project in Docker
-        run: |
-          docker run --rm -v "$(pwd)":/app -w /app books-users-app mvn package \
-          -Dspring.profiles.active=ci
-
-      - name: Check if JAR file exists
-        run: |
-          if [ ! -f target/*.jar ]; then
-            echo "JAR file not found!"
-            exit 1
-          fi
-
-      - name: Publish Unit Test Results
-        uses: EnricoMi/publish-unit-test-result-action@v2
-        if: always()
-        with:
-          check_name: 'Maven Test Results'
-          junit_files: target/surefire-reports/**/*.xml
-
-      - name: Upload JAR to Remote Server
-        env:
-          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-          REMOTE_USER: ${{ secrets.SSH_USER }}
-          REMOTE_HOST: ${{ secrets.SSH_HOST }}
-          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
-        run: |
-          mkdir -p ~/.ssh
-          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/github_rsa
-          chmod 400 ~/.ssh/github_rsa
-          ssh-keyscan ${REMOTE_HOST} >> ~/.ssh/known_hosts
-          scp -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no target/*.jar ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}
-
-      - name: Send Dooray Webhook on Success
-        if: success()
-        uses: actions/github-script@v6
-        env:
-          PR_URL: ${{ github.event.pull_request.html_url }}
-          PR_TITLE: ${{ github.event.pull_request.title }}
-          PR_ACTOR: ${{ github.actor }}
-          DOORAY_WEBHOOK_URL: ${{ secrets.DOORAY_WEBHOOK_URL }}
-        with:
-          script: |
-            const webhookUrl = process.env.DOORAY_WEBHOOK_URL;
-            const payload = {
-              botName: "도서 회원 서버 Bot",
-              botIconImage: "https://www.tistory.com/favicon.ico",
-              text: "도서 회원 서버의 Pull Request가 성공적으로 올라갔어요!",
-              attachments: [
-                {
-                  title: "Pull Request URL",
-                  titleLink: process.env.PR_URL,
-                  color: "green",
-                  text: `PR 제목: ${process.env.PR_TITLE}, PR 작성자: ${process.env.PR_ACTOR}`
-                }
-              ]
-            };
-
-            const response = await fetch(webhookUrl, {
-              method: 'POST',
-              headers: {
-                'Content-Type': 'application/json'
-              },
-              body: JSON.stringify(payload)
-            });
-
-            if (!response.ok) {
-              throw new Error(`Failed to send webhook: ${response.statusText}`);
-            }
-
-      - name: Send Dooray Webhook on Failure
-        if: failure()
-        uses: actions/github-script@v6
-        env:
-          PR_URL: ${{ github.event.pull_request.html_url }}
-          PR_TITLE: ${{ github.event.pull_request.title }}
-          PR_ACTOR: ${{ github.actor }}
-          DOORAY_WEBHOOK_URL: ${{ secrets.DOORAY_WEBHOOK_URL }}
-        with:
-          script: |
-            const webhookUrl = process.env.DOORAY_WEBHOOK_URL;
-            const payload = {
-              botName: "도서 회원 서버 Bot",
-              botIconImage: "https://www.tistory.com/favicon.ico",
-              text: "도서 회원 서버의 Pull Request가 실패했어요...",
-              attachments: [
-                {
-                  title: "Pull Request URL",
-                  titleLink: process.env.PR_URL,
-                  color: "red",
-                  text: `PR 제목: ${process.env.PR_TITLE}, PR 작성자: ${process.env.PR_ACTOR}`
-                }
-              ]
-            };
-
-            const response = await fetch(webhookUrl, {
-              method: 'POST',
-              headers: {
-                'Content-Type': 'application/json'
-              },
-              body: JSON.stringify(payload)
-            });
-
-            if (!response.ok) {
-              throw new Error(`Failed to send webhook: ${response.statusText}`);
-            }
+#name: Java CI with Docker
+#
+#on:
+#  pull_request:
+#    branches: [ "develop" ]
+#
+#permissions: write-all
+#
+#jobs:
+#  build:
+#    runs-on: ubuntu-latest
+#
+#    steps:
+#      - name: Checkout code
+#        uses: actions/checkout@v3
+#
+#      - name: Verify Dockerfile exists
+#        run: |
+#          if [ ! -f Dockerfile ]; then
+#            echo "Dockerfile not found!"
+#            exit 1
+#          fi
+#
+#      - name: Build Docker image
+#        run: |
+#          docker build --no-cache -t books-users-app .
+#
+#      - name: Run Maven tests in Docker
+#        run: |
+#          docker run --rm books-users-app mvn clean verify sonar:sonar \
+#          -Dspring.profile.active=ci \
+#          -Dsonar.projectKey=yes-25-5-books-users \
+#          -Dsonar.projectName='yes-25-5-books-users' \
+#          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
+#          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
+#
+#      - name: Build Maven project in Docker
+#        run: |
+#          docker run --rm -v "$(pwd)":/app -w /app books-users-app mvn package \
+#          -Dspring.profiles.active=ci
+#
+#      - name: Check if JAR file exists
+#        run: |
+#          if [ ! -f target/*.jar ]; then
+#            echo "JAR file not found!"
+#            exit 1
+#          fi
+#
+#      - name: Publish Unit Test Results
+#        uses: EnricoMi/publish-unit-test-result-action@v2
+#        if: always()
+#        with:
+#          check_name: 'Maven Test Results'
+#          junit_files: target/surefire-reports/**/*.xml
+#
+#      - name: Upload JAR to Remote Server
+#        env:
+#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+#          REMOTE_USER: ${{ secrets.SSH_USER }}
+#          REMOTE_HOST: ${{ secrets.SSH_HOST }}
+#          REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
+#        run: |
+#          mkdir -p ~/.ssh
+#          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/github_rsa
+#          chmod 400 ~/.ssh/github_rsa
+#          ssh-keyscan ${REMOTE_HOST} >> ~/.ssh/known_hosts
+#          scp -i ~/.ssh/github_rsa -o StrictHostKeyChecking=no target/*.jar ${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}
+#
+#      - name: Send Dooray Webhook on Success
+#        if: success()
+#        uses: actions/github-script@v6
+#        env:
+#          PR_URL: ${{ github.event.pull_request.html_url }}
+#          PR_TITLE: ${{ github.event.pull_request.title }}
+#          PR_ACTOR: ${{ github.actor }}
+#          DOORAY_WEBHOOK_URL: ${{ secrets.DOORAY_WEBHOOK_URL }}
+#        with:
+#          script: |
+#            const webhookUrl = process.env.DOORAY_WEBHOOK_URL;
+#            const payload = {
+#              botName: "도서 회원 서버 Bot",
+#              botIconImage: "https://www.tistory.com/favicon.ico",
+#              text: "도서 회원 서버의 Pull Request가 성공적으로 올라갔어요!",
+#              attachments: [
+#                {
+#                  title: "Pull Request URL",
+#                  titleLink: process.env.PR_URL,
+#                  color: "green",
+#                  text: `PR 제목: ${process.env.PR_TITLE}, PR 작성자: ${process.env.PR_ACTOR}`
+#                }
+#              ]
+#            };
+#
+#            const response = await fetch(webhookUrl, {
+#              method: 'POST',
+#              headers: {
+#                'Content-Type': 'application/json'
+#              },
+#              body: JSON.stringify(payload)
+#            });
+#
+#            if (!response.ok) {
+#              throw new Error(`Failed to send webhook: ${response.statusText}`);
+#            }
+#
+#      - name: Send Dooray Webhook on Failure
+#        if: failure()
+#        uses: actions/github-script@v6
+#        env:
+#          PR_URL: ${{ github.event.pull_request.html_url }}
+#          PR_TITLE: ${{ github.event.pull_request.title }}
+#          PR_ACTOR: ${{ github.actor }}
+#          DOORAY_WEBHOOK_URL: ${{ secrets.DOORAY_WEBHOOK_URL }}
+#        with:
+#          script: |
+#            const webhookUrl = process.env.DOORAY_WEBHOOK_URL;
+#            const payload = {
+#              botName: "도서 회원 서버 Bot",
+#              botIconImage: "https://www.tistory.com/favicon.ico",
+#              text: "도서 회원 서버의 Pull Request가 실패했어요...",
+#              attachments: [
+#                {
+#                  title: "Pull Request URL",
+#                  titleLink: process.env.PR_URL,
+#                  color: "red",
+#                  text: `PR 제목: ${process.env.PR_TITLE}, PR 작성자: ${process.env.PR_ACTOR}`
+#                }
+#              ]
+#            };
+#
+#            const response = await fetch(webhookUrl, {
+#              method: 'POST',
+#              headers: {
+#                'Content-Type': 'application/json'
+#              },
+#              body: JSON.stringify(payload)
+#            });
+#
+#            if (!response.ok) {
+#              throw new Error(`Failed to send webhook: ${response.statusText}`);
+#            }
